---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/bots":
    get:
      summary: 查詢所有機器人
      tags:
      - Bots
      security:
      - bearerAuth: []
      responses:
        '200':
          description: ok.
        '401':
          description: Unauthorized
    post:
      summary: 註冊機器人
      tags:
      - Bots
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created.
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: bot1
                webhook_url:
                  type: string
                  example: https://localhost:3000/mybot/c8763
                concurrent_number:
                  type: integer
                  example: 1
  "/api/v1/bots/{id}":
    get:
      summary: 查詢機器人
      tags:
      - Bots
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
        '401':
          description: Unauthorized
        '404':
          description: Not Found
    put:
      summary: 更新機器人(replace)
      tags:
      - Bots
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: bot1
                webhook_url:
                  type: string
                  example: https://localhost:3000/mybot/c8763
                concurrent_number:
                  type: integer
                  example: 1
    patch:
      summary: 更新機器人(partial)
      tags:
      - Bots
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: bot1
                webhook_url:
                  type: string
                  example: https://localhost:3000/mybot/c8763
                concurrent_number:
                  type: integer
                  example: 1
    delete:
      summary: 刪除機器人
      tags:
      - Bots
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: ok.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  "/api/v1/rooms/{room_id}/game":
    post:
      summary: 開始遊戲
      tags:
      - Games
      security:
      - bearerAuth: []
      parameters:
      - name: room_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: ok.
    get:
      summary: 查詢目前遊戲狀態
      tags:
      - Games
      security:
      - bearerAuth: []
      parameters:
      - name: room_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
    delete:
      summary: 結束遊戲
      tags:
      - Games
      security:
      - bearerAuth: []
      parameters:
      - name: room_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
  "/api/v1/rooms/{room_id}/game/play-unit":
    post:
      summary: 放入棋子
      tags:
      - Games
      security:
      - bearerAuth: []
      parameters:
      - name: room_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                x:
                  type: integer
                "y":
                  type: integer
  "/api/v1/rooms/{room_id}/game/split":
    post:
      summary: 分配棋子
      tags:
      - Games
      security:
      - bearerAuth: []
      parameters:
      - name: room_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                origin_x:
                  type: integer
                origin_y:
                  type: integer
                target_x:
                  type: integer
                target_y:
                  type: integer
                amount:
                  type: integer
  "/api/v1/preferences":
    patch:
      summary: 更新偏好設定
      tags:
      - Users/Preferences
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: ok.
        '304':
          description: not modified.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
    get:
      summary: 查詢偏好設定
      tags:
      - Users/Preferences
      security:
      - bearerAuth: []
      responses:
        '200':
          description: ok.
  "/api/v1/rooms":
    get:
      summary: 查詢房間列表
      tags:
      - Rooms
      security:
      - bearerAuth: []
      responses:
        '200':
          description: ok.
    post:
      summary: 開啟房間
      tags:
      - Rooms
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: ok.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
  "/api/v1/rooms/{id}":
    get:
      summary: 查詢房間資料
      tags:
      - Rooms
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
    patch:
      summary: 更新房間資料
      tags:
      - Rooms
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
        '404':
          description: not found.
        '401':
          description: unauthorized.
        '403':
          description: forbidden.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
  "/api/v1/rooms/{id}/close":
    post:
      summary: 關閉房間
      tags:
      - Rooms
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
  "/api/v1/rooms/{id}/knock-knock":
    get:
      summary: 取得加入房間 token
      tags:
      - Rooms
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok.
        '404':
          description: not found.
        '401':
          description: unauthorized.
        '422':
          description: unprocessable entity. see response.error.
  "/api/v1/users":
    post:
      summary: 登入
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: ok.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
    get:
      summary: 查詢線上使用者
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: ok.
  "/api/v1/me":
    get:
      summary: 查詢個人資料
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: ok.
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: https://spt-games-split.zeabur.app
      enum:
      - https://spt-games-split.zeabur.app
      - http://localhost:3000
